Will an if statement in the pipeline do the trick?

diff --git a/.github/workflows/secureliCI.yml b/.github/workflows/secureliCI.yml
--- a/.github/workflows/secureliCI.yml
+++ b/.github/workflows/secureliCI.yml
@@ -42,7 +42,13 @@ jobs:
         cp .pre-commit-config.yaml pyproject.toml python-secrets/
         cd python-secrets
         poetry install
-        poetry run poe precommit
+        if $(poetry run poe precommit); then
+          echo "Test failed!"
+          exit 1
+        else
+          echo "Test succeeded!"
+          continue
+        fi
     - name: Semantic Release
       if: github.event_name == 'push' && github.ref == 'refs/heads/main'
       run: |
